= GLOBUS LS(1)

== NAME

globus ls - List endpoint directory contents

== SYNOPSIS

*globus ls* ['OPTIONS'] 'ENDPOINT_ID[:PATH]'


== DESCRIPTION

The *globus ls* command lists files and subdirectories on an endpoint. If no
path is given, the default directory on that endpoint will be used.

If using text output files and directories are printed with one entry per
line in alphabetical order.  Directories are always displayed with a
trailing '/'.

include::include/cli_autoactivate.adoc[]


== OPTIONS

*-a, --all*::

Show hidden files and directories that start with '.'

*-l, --long*::

Long form tabular output similar to 'ls -l'.

*-r, --recursive*::

Do a recursive listing similar to 'ls -R' only goes as deep as allowed by
the --recursive-depth-limit. Note that this can quickly become a very expensive
operation and may take a significant amount of time to complete or even fail on
rate limits.

*--recursive-depth-limit*::

Set the depth limit when using the --recursive option. Defaults to 3 if not
given.

*--filter* 'FILTER_PATTERN'::

Filter results to filenames matching the given pattern.
+
Filter patterns must start with `=`, `~`, `!`, or `!~`
If none of these are given, `=` will be used
+
`=` does exact matching
+
`~` does regex matching, supporting globs (*)
+
`!` does inverse `=` matching
+
`!~` does inverse `~` matching
+
See the examples section for various forms of usage.

include::include/common_options.adoc[]


== EXAMPLES

List files and dirs in your default directory on an endpoint.

----
$ ep_id=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ globus ls $ep_id
----

List files and dirs on a specific path on an endpoint.

----
$ ep_id=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ globus ls $ep_id:/share/godata/
----

List files and dirs on a specific path on an endpoint, filtering in various
ways.

----
$ ep_id=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ globus ls $ep_id:/share/godata/ --filter '~*.txt'  # all txt files
$ globus ls $ep_id:/share/godata/ --filter '!~file1.*'  # not starting in "file1."
$ globus ls $ep_id:/share/godata/ --filter '~*ile3.tx*'  # anything with "ile3.tx"
$ globus ls $ep_id:/share/godata/ --filter '=file2.txt'  # only "file2.txt"
$ globus ls $ep_id:/share/godata/ --filter 'file2.txt'  # same as '=file2.txt'
$ globus ls $ep_id:/share/godata/ --filter '!=file2.txt'  # anything but "file2.txt"
----

Compare a grep with a `globus ls --filter`. These two are the same, but the
filter will be faster because it doesn't require that filenames which are
filtered out are returned to the CLI:

----
$ ep_id=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ globus ls $ep_id:/share/godata/ | egrep '*.txt'  # done with grep, okay
$ globus ls $ep_id:/share/godata/ --filter '~*.txt'  # done with --filter, better
----


include::include/exit_status.adoc[]
