= GLOBUS SESSION UPDATE(1)

== NAME

globus session update - Update the user's CLI auth session


== SYNOPSIS

*globus session update* ['OPTIONS'] ['UUID_OR_USERNAME(s)']


== DESCRIPTION

The *globus session update* command starts an authentication
flow with Globus Auth similarly to *globus login* but specifies which
identities to authenticate with.

After successful authentication, the user's CLI auth session will be updated
with any new identities and current Auth Times.

The given UUIDs or usernames must be in the user's identity set.


== OPTIONS

*--all*::

Shortcut to specify that the user wants to authenticate with every
identity in their identity set rather than list them all as separate
arguments. If this option is given, no UUID_OR_USERNAME arguments
should be given.

*--no-local-server*::

Use manual authentication. You will be given a link to follow and must respond
with a copied and pasted access code from that link. Implied if the CLI
detects you are on a remote session.

include::include/help_option.adoc[]

include::include/verbose_option.adoc[]


include::include/exit_status_no_http.adoc[]
