= GLOBUS TASK PAUSE-INFO(1)

== NAME

globus task pause-info - Show why a Task is paused


== SYNOPSIS

*globus task pause-info* ['OPTIONS'] 'TASK_ID'


== DESCRIPTION

The *globus task pause-info* command shows messages from activity managers who
have explicitly paused the given in-progress task and list any active pause
rules that apply to it.
It displays no information for tasks which are not paused.

== OPTIONS

include::include/common_options.adoc[]

== OUTPUT

When text output is requested, output is broken apart into explicit pause rules
applied to the specific task (explicit pauses), and "effective pause rules"
which apply to the task by virtue of the endpoint(s) it uses.

Explicit pauses are listed with any of the following fields which apply:

- 'Source Endpoint'
- 'Source Shared Endpoint'
- 'Destination Endpoint'
- 'Destination Shared Endpoint'

which refer to the messages which may be set by these various endpoints.

Effective pause rules are listed with these fields:

- 'Operations'
- 'On Endpoint'
- 'All Users'
- 'Message'


== EXAMPLES

Show why a task is paused, producing JSON output:

----
$ globus task pause-info TASK_ID --format JSON
----

include::include/exit_status.adoc[]
