= GLOBUS TASK LIST(1)

== NAME

globus task list - List tasks for the current user

== SYNOPSIS

*globus task list* ['OPTIONS']

== DESCRIPTION

The *globus task list* command lists the current user's most recent tasks. The
tasks displayed may be filtered by a number of attributes, each with a separate
commandline option.


== OPTIONS

*--limit* 'N'::

Limit the number of results to the 'N' most recent. Default value is 10.

*--filter-task-id* 'UUID'::

Filter the tasks to those matching this UUID. This option can be
used multiple times, meaning that any matching Task IDs are allowed.

*--filter-type* '[TRANSFER|DELETE]'::

Filter results to only 'TRANSFER' or 'DELETE' tasks.

*--filter-status* '[ACTIVE|INACTIVE|FAILED|SUCCEEDED]'::

Task status to filter results by. This option can be used multiple times,
meaning that any matching status is allowed.

*--filter-label* 'TEXT'::

Filter results to task whose label matches a pattern. This option can be used
multiple times, meaning that any matching label is allowed.

*--filter-not-label* 'TEXT'::

Filter results whose label does not match a pattern. This option can be used
multiple times, meaning any non-matching patterns are excluded.

*--inexact/--exact*::

When *--exact* is given *--filter-label* and *--filter-not-label* must be exact
matches. When *--inexact* is given, these patterns may include '*' as a
wild-card, and may ignore case.

*--filter-requested-after* 'ISO_TIME'::

Filter results to tasks that were requested after given time.

*--filter-requested-before* 'ISO_TIME'::

Filter results to tasks that were requested before given time.

*--filter-completed-after* 'ISO_TIME'::

Filter results to tasks that were completed after given time.

*--filter-completed-before* 'ISO_TIME'::

Filter results to tasks that were completed before given time.

include::include/common_options.adoc[]

== OUTPUT

When text output is requested, the following fields are used:

- 'Task ID'
- 'Status'
- 'Type'
- 'Source Display Name'
- 'Dest Display Name'
- 'Label'


== EXAMPLES

List results in a text table:

----
$ globus task list
----

List the first 100 tasks which were completed between May 2015 and July 2015,
but whose labels aren't the exact string 'autolabel':

----
$ globus task list --limit 100 \
    --filter-completed-after 2015-05-01 \
    --filter-completed-before 2015-07-30 \
    --filter-not-label 'autolabel' --exact
----

List active transfers in a tabular format suitable for consumption by unix
tools:

----
$ globus task list --format unix \
    --jmespath 'DATA[?status==`ACTIVE`].[task_id, source_endpoint_id, destination_endpoint_id, label]'
----

NOTE: 'destination_endpoint_id' will be 'None' in the case of Delete tasks.

Cancel all tasks with expired credentials:

----
# careful: do not quote this output, but instead rely on the shell's
# word-splitting for this for-loop
for id in $(globus task list --filter-status=INACTIVE \
                             --format=UNIX \
                             --jmespath='DATA[*].task_id'); do
    globus task cancel $id
done
----

Print out task statuses with links to their pages in the web UI:

----
globus task list --format=unix --jmespath='DATA[*].[task_id, status]' | \
    awk '{printf "Task %s is currently %s\n", $1, $2;
          printf "View at https://app.globus.org/activity/%s\n\n", $1}'
----

include::include/exit_status.adoc[]
