= GLOBUS WHOAMI(1)

== NAME

globus whoami - Show the currently logged-in identity.

== SYNOPSIS

*globus whoami* ['OPTIONS']

== DESCRIPTION

The *globus whoami* command will display information for the currently
logged-in user.


== OPTIONS

*--linked-identities* ::

Show the full identity set of the currently logged in identity, which contains
the primary identity and any identities linked to it.

include::include/format_option.adoc[]

include::include/help_option.adoc[]

include::include/verbose_option.adoc[]


== OUTPUT

If no options are given the default output is just the preferred
username of the logged in identity.

If *--linked-identities* is given the output will be each username in the
logged-in user's identity set.

If *--verbose* is given, the following fields will be output, either in
a record format or a table format if *--linked-identities* is also given.

- 'Username'
- 'Name'
- 'ID'
- 'Email'


== EXAMPLES

Display multiple fields of the current user's information:

----
$ globus whoami -v
----

Display each username in the current user's identity set:

----
$ globus whoami --linked-identities
----

include::include/exit_status_no_http.adoc[]
